version: "3"
services:
  test-web:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:80"
  test-api:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5000:5000"
  test-postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - "5432:5432"
