version: "3"
services:
  postgres:
    image: "postgres:latest"
    env_file:
      - ./backend/.production.env
    environment:
      - POSTGRES_PORT=5432

  api:
    build:
      dockerfile: Dockerfile.server
      context: "./backend"
    env_file:
      - ./backend/.production.env
    environment:
      - POSTGRES_PORT=5432

    ports:
      - 5000:5000
    depends_on:
      - postgres

  client:
    build:
      dockerfile: Dockerfile.client
      context: ./front
    ports:
      - 8080:80
