version: "3"
services:
  postgres:
    image: "postgres:latest"
    env_file:
      - ./backend/.production.env

  api:
    build:
      dockerfile: Dockerfile.server
      context: "./backend"
    env_file:
      - ./backend/.production.env

    ports:
      - 5000:5000
    depends_on:
      - postgres

  client:
    build:
      dockerfile: Dockerfile.client
      context: ./front
    ports:
      - 3000:80

volumes:
  pgdata:
