FROM node:14.14.0-alpine as builder

WORKDIR /app

COPY ./package.json ./

RUN npm i

COPY . .

RUN npm run build

# runner
#---------------------------------------------
FROM nginx:1.13.3-alpine AS final

RUN rm -rf /usr/share/nginx/html/*

COPY ./default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]